### PR TITLE
Added ReadOPM plugin

### PR DESCRIPTION
**Pull request by Danatobob**
ww3.readopm.com is a One Punch Man manga website.
Also since all files were initially downloaded into "p.txt" (thats the name in request response) I had to fix this in Downloader.cs. The issue is not specific to that site as I saw the same thing when I tried MangaRipper on supported sites and thought the program is broken.

### CODE REVIEW

**Comment by NguyenDanPhuong** [comment]
I've checked the site and filename returned correctly from server. It's not .txt. It seems your network or ISP having problems. Can you verify again?

**Comment by Danatobob** [comment]
Hmm, that might be the case if it works for you. Didn't think of it that way. Anyways I've tried it from my office pc (which should have different provider i think) and got same results. The steps to repro this is easy:
1. open in browser: 
http://ww3.readopm.com/chapter/one-punch-man-chapter-001/

2. right click on any manga image and select "save image as...". The suggested name will be "p.txt".

If it's different for you, then I don't know. It might be useful to leave my fix as there could be more users like me not understanding whats going on with "p.txt" and stuff (btw I think I got at least once some other filename). The fix is kinda messy though so maybe it should be improved somehow (like checking for png/jpg/etc. image extensions).

**Comment by NguyenDanPhuong** [comment]
I can repro this now. Let's merge this, I have a good design for this feature already and I will refactoring it later.

**Comment by Danatobob** [comment]
Allright. Glad I could contribute to this project as it saved me time and headache.

**Pull request merged**
