### PR TITLE
[Do not merge yet] Add Alternative Links logic, and test it on MangaStream.

### PR DESCRIPTION
**Pull request by GambitKZ**
@NguyenDanPhuong  @JedBurke could you please take a look at this Pull Request.
I thinking of implementing alternative Url logic, which allows users easily change the address of the server if it will be moved, or mirror address will pop up.
All they need to do is to put the link(s) into the configuration. For example, for  Mangafox it will be something like "Plugin.MangaFox.AlternativeLinks": "mangafox.mirror.com".
The configuration will be taken during plugin initialization, and if the method is overridden, all you need to do is to call "base.Configuration(settings);".
What do you think?
#104

### CODE REVIEW

**Comment by JedBurke** [comment]
@GambitKZ

I 100% agree with the idea of being able to override the domains.

That said, I'm on VS 2012 for the time being, so I can't compile the code. :/ If I understand it correctly, the alternative links will be specified in MangaRipper's configuration file? 

What if each plugin get its own configuration file? It may take some reworking, but a lot of reoccurring issues (URL and pattern changes) can be solved without its recompilation while keeping the main configuration file uncluttered.

Consider the following directory structure.

```
.
`-- MangaRipper
    |-- mangaripper.exe
    `-- plugins
        |-- kissmanga
        |    |-- config.ini (or config.json)
        |    `-- plugin.dll
        |-- mangafox
        |    |-- config.ini
        |    `-- plugin.dll
        `-- mangahere
            |-- config.ini
             `-- plugin.dll
```

Inside `config.json`
```JSON
{
    "url": [
        "mangafox.com",
        "mangafox.me",
        "mangafox.la",
        "mangafox.xyz"
    ],
    "chapter_path": "escaped_regex",
    "page_path": "escaped_regex"
}
```

The URL may be stored inside an array, so all the user or developer needs to do is add a new or replace the old one.

**Comment by GambitKZ** [comment]
Well, I believe the main idea was to keep everything in one config file. And in mine opinion, it's also the good solution to keep configurations in one place. In my code Urls are separated by comma sign. So it will be:
"Plugin.MangaFox.AlternativeLinks": "mangafox.com,mangafox.me,mangafox.la,mangafox.xyz"

The same can go with RegEx. Good idea by the way.

@NguyenDanPhuong you're the boss, so what do you think?

**Comment by JedBurke** [comment]
All right. What I said earlier stands though, it's good to be able to override the settings, regardless of how you and @NguyenDanPhuong want to implement it.

**Comment by NguyenDanPhuong** [comment]
I've trying to make it easier to replace regex. I've moved some parser from regex to xpath selector in my latest commit. Hopefully it will make this kind of feature easier to implement. But I'd say we still far from a good design that allow 'clean' implementation of this feature.

**Pull request closed without merging**
